# Generated by Django 5.2.8 on 2025-11-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Indie', 'Indie'), ('Reggaeton', 'Reggaeton'), ('Salsa', 'Salsa'), ('Hip Hop', 'Hip Hop'), ('Dembow', 'Dembow'), ('Bachata', 'Bachata')], max_length=20)),
            ],
        ),
    ]
