# Generated by Django 5.2.8 on 2025-11-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl', '0002_categoria_album_precio_album_stock_album_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('VIP', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Indie Rock', 'Indie Rock'), ('Indie Pop', 'Indie Pop'), ('Alternative Rock', 'Alternative Rock'), ('Metal', 'Metal'), ('Punk', 'Punk'), ('Pop', 'Pop'), ('K-pop', 'K-pop'), ('J-pop', 'J-pop'), ('Jazz', 'Jazz'), ('Blues', 'Blues'), ('Disco', 'Disco'), ('Salsa', 'Salsa'), ('Bachata', 'Bachata'), ('Reggaeton', 'Reggaeton'), ('Cumbia', 'Cumbia'), ('Dembow', 'Dembow'), ('Bolero', 'Bolero'), ('Electronica', 'Electronica'), ('Techno', 'Techno'), ('Hip Hop', 'Hip Hop'), ('Reggae', 'Reggae')], max_length=20),
        ),
    ]
