# Generated by Django 5.2.8 on 2025-11-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl', '0003_usuario_alter_album_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='categoria',
        ),
        migrations.AddField(
            model_name='album',
            name='BESTSELLER',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='album_images/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('NN', 'No definido'), ('Rock', 'Rock'), ('Indie Rock', 'Indie Rock'), ('Indie Pop', 'Indie Pop'), ('Alternative Rock', 'Alternative Rock'), ('Metal', 'Metal'), ('Punk', 'Punk'), ('Pop', 'Pop'), ('K-pop', 'K-pop'), ('J-pop', 'J-pop'), ('Jazz', 'Jazz'), ('Blues', 'Blues'), ('Disco', 'Disco'), ('Salsa', 'Salsa'), ('Bachata', 'Bachata'), ('Reggaeton', 'Reggaeton'), ('Cumbia', 'Cumbia'), ('Dembow', 'Dembow'), ('Bolero', 'Bolero'), ('Electronica', 'Electronica'), ('Techno', 'Techno'), ('Hip Hop', 'Hip Hop'), ('Reggae', 'Reggae'), ('Trap', 'Trap')], default='NN', max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='album',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
