# Generated by Django 5.2.8 on 2025-12-02 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl', '0005_compra_compraitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vinyl.categoria'),
        ),
    ]
